### ISSUE TITLE
ToDoList

### ISSUE THREAD

**Issue by Vadim-Maletskii** [DataAccess2020/CE1_Korotkikh_Maletskii#1]
1. Find a viable research question
2. Specify an empirical hypothesis addressing the research question
3. Test the empirical hypothesis, including at least 1 visual and 1 numeric/statistical test
4. Draw a conclusion
5. Create Rmarkdown report, imorting everthing there

**Comment by skorotkikh** [comment]
1.  Is there a relationship between people's trust in police and them feeling safe alone outside at night?
2.  People who trust the police more feel safer alone outside at night.

**Comment by skorotkikh** [comment]
3. Tests completed, a PNG file with the results created

**Comment by skorotkikh** [comment]
The relationship seems weird because in the independent variable 10 is the "best" value and 1 is the "worst", where in the dependent 1 is the "best" and 4 is the "worst". We need to recode the values of the dependent variable
